### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: A Microsoft System Center Configuration Manager 2007 R2 a rögzített életciklusra vonatkozó szabályzatot követi.
  ms.date: 07/28/2020
  ms.openlocfilehash: 0da71b9a2886e1a7012339ebef9a5fbe64f8811e
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "822230"
name: Microsoft System Center Configuration Manager 2007 R2
summary: >
  A Microsoft System Center Configuration Manager 2007 R2 a rögzített életciklusra [vonatkozó](/lifecycle/policies/fixed) szabályzatot követi.



  > [!IMPORTANT]

  > A termék támogatása véget ért. Lásd az áttelepítési útmutatót alább.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Linkek \n* [Migrációs útmutató](/mem/configmgr/core/migration/planning-for-migration)\n* [További áttelepítési útmutató](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
