### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: A Microsoft Forefront Client Security a rögzített életciklus-házirendet követi.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924258"
name: Microsoft Forefront Client Security
summary: >+
  A Microsoft Forefront Client Security a [rögzített](/lifecycle/policies/fixed) életciklus-házirendet követi.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Hivatkozások \n* [Végpont-védelem a System Center alkalmazásban](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> A Forefront Client Security megszűnt a július 14., 2015. Az antimalware-és antispyware-definíciók frissítései a továbbiakban nem lesznek elérhetők a termékek verziójának támogatása után. Kérjük, értékelje ki a System Center Endpoint Protectiont csereként."
