### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: A Microsoft Application Virtualization 5.1 a Rögzített Életciklus Szabályzatot követi.
  ms.date: 09/10/2020
  keywords: for Remote Desktop Services,for Windows Desktops
  ms.openlocfilehash: 5ebb28c8965d47f928547b36980e68ed6cc9c791
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4155702"
name: Microsoft Application Virtualization 5.1
summary: >+
  A Microsoft Application Virtualization 5.1 a [Rögzített](/lifecycle/policies/fixed) Életciklus Szabályzatot követi.


  Ez a következő kiadásokra vonatkozik: Távoli asztali szolgáltatásokhoz, Windows asztali számítógépekhez

products:
- windows
policyType: fixed
supportDates:
  start: 2015-11-01T00:00:00.000-08:00
  end: 2018-01-09T22:59:59.999-08:00
  extendedEnd: 2026-04-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2015-11-01T00:00:00.000-08:00
  endDate: 2026-04-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Hivatkozások \n* [Termékinformációk](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Kiadások \n* távoli asztali szolgáltatásokhoz\n* Windows asztali számítógépek esetén"
