### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007
  description: A Microsoft System Center Configuration Manager 2007 a Rögzített Életciklus Szabályzatot követi.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007
summary: |
  A Microsoft System Center Configuration Manager 2007 a [Rögzített](/lifecycle/policies/fixed) Életciklus Szabályzatot követi.


  > [!IMPORTANT]
  > A termék támogatása lejárt. Lásd lejjebb az áttelepítési útmutatót.
products:
  - msc
policyType: fixed
supportDates:
  start: 11/29/2007
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Service Pack 2
    startDate: 10/22/2009
    endDate: 07/09/2019
  - version: Service Pack 1
    startDate: 05/21/2008
    endDate: 01/11/2011
  - version: Original Release
    startDate: 11/29/2007
    endDate: 07/14/2009
content: |+

  ## <a name="links"></a>Hivatkozások 
  * [Áttelepítési útmutató](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Termékinformációk](/mem/configmgr/core/understand/introduction)
  * [Szervizcsomag-szabályzat](/lifecycle/policies/fixed#service-packs)