### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.0 Windows asztali gépekre
  description: A Microsoft Application Virtualization Hosting 5.0 for Windows Desktops a Rögzített Életciklus Szabályzatot követi.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.0 Windows asztali gépekre
summary: |+
  A Microsoft Application Virtualization Hosting 5.0 for Windows Desktops a [Rögzített](/lifecycle/policies/fixed) Életciklus Szabályzatot követi.

  Ez a következő kiadásokra vonatkozik: Windows asztali gépekre

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Service Pack 3
    startDate: 12/08/2014
    endDate: 04/14/2026
  - version: Service Pack 2
    startDate: 11/08/2013
    endDate: 01/12/2016
  - version: Service Pack 1
    startDate: 04/10/2013
    endDate: 01/13/2015
  - version: Original Release
    startDate: 11/01/2012
    endDate: 07/08/2014
content: |

  ## <a name="links"></a>Hivatkozások 
  * [Termékinformációk](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Szervizcsomag-szabályzat](/lifecycle/policies/fixed#service-packs)


  ## <a name="editions"></a>Kiadások 
  * Windows asztali számítógépek esetén