### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 R2 Konfigurációkezelő
  description: A Microsoft System Center 2012 R2 Konfigurációkezelő a Rögzített Életciklus Szabályzatot követi.
  ms.date: 07/28/2020
  ms.openlocfilehash: 61515e636a9af310a2107c9505067fa551d26b15
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: HT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "855814"
name: Microsoft System Center 2012 R2 Konfigurációkezelő
summary: >+
  A Microsoft System Center 2012 R2 Konfigurációkezelő a [Rögzített](/lifecycle/policies/fixed) Életciklus Szabályzatot követi.


products:
- msc
policyType: fixed
supportDates:
  start: 01/16/2014
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 1
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Original Release
  startDate: 01/16/2014
  endDate: 07/12/2016
content: "\n## <a name=\"links\"></a>Hivatkozások \n* [Szervizcsomag-szabályzat](/lifecycle/policies/fixed#service-packs)\n* [A Konfigurációkezelő dokumentációja](/mem/configmgr/core/misc/online-documentation)"
