### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 R2 Konfigurációkezelő
  description: A Microsoft System Center 2012 R2 Konfigurációkezelő a Rögzített Életciklus Szabályzatot követi.
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: 9e7bbf1db9f64b796da4e0c31bf66ce1b7dea0367121fbaeb1f2f41e60a20772
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2523675"
name: Microsoft System Center 2012 R2 Konfigurációkezelő
summary: >+
  A Microsoft System Center 2012 R2 Konfigurációkezelő a [Rögzített](/lifecycle/policies/fixed) Életciklus Szabályzatot követi.


products:
- msc
policyType: fixed
supportDates:
  start: 01/16/2014
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 1
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Original Release
  startDate: 01/16/2014
  endDate: 07/12/2016
content: "\n## <a name=\"links\"></a>Hivatkozások \n* [Szervizcsomag-szabályzat](/lifecycle/policies/fixed#service-packs)\n* [A Konfigurációkezelő dokumentációja](/mem/configmgr/core/misc/online-documentation)\n* [Áttelepítési útmutató](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
