### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: A Microsoft Forefront Client Security a rögzített életciklus-szabályzatot követi.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  A Microsoft Forefront Client Security a [rögzített](/lifecycle/policies/fixed) életciklus-szabályzatot követi.


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Hivatkozások 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > 2015. július 14-től megszűnt a Forefront Client Security. A kártevőirtó és kémprogram-elhárító definíciós frissítések a termékverzió támogatásának megszűnését követően már nem lesznek elérhetők. Kérjük, értékelje ki a System Center Endpoint Protection-t helyettesítőként.