### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: A Microsoft Forefront Client Security a rögzített életciklus-szabályzatot követi.
  ms.date: 08/28/2020
  ms.openlocfilehash: d85aea21441458397839241e74939536051397d4
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4113411"
name: Microsoft Forefront Client Security
summary: >+
  A Microsoft Forefront Client Security a [rögzített](/lifecycle/policies/fixed) életciklus-szabályzatot követi.


products:
- msc
policyType: fixed
supportDates:
  start: 2007-08-02T00:00:00.000-08:00
  extendedEnd: 2015-07-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-08-02T00:00:00.000-08:00
  endDate: 2015-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Hivatkozások \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> 2015. július 14-től megszűnt a Forefront Client Security. A kártevőirtó és kémprogram-elhárító definíciós frissítések a termékverzió támogatásának megszűnését követően már nem lesznek elérhetők. Kérjük, értékelje ki a System Center Endpoint Protection-t helyettesítőként."
