### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager (LTSB - 1606-os verzió)
  description: A Microsoft System Center Configuration Manager (LTSB - 1606-os verzió) a rögzített életciklus-szabályzatot követi.
  ms.date: 08/20/2020
  ms.openlocfilehash: 6475679aee15c8748a0fc3092509dee7010472d848ac73e54be2c605a19595e5
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2511243"
name: Microsoft System Center Configuration Manager (LTSB - 1606-os verzió)
summary: >+
  A Microsoft System Center Configuration Manager (LTSB - 1606-os verzió) a [rögzített](/lifecycle/policies/fixed) életciklus-szabályzatot követi.


products:
- m365
policyType: fixed
supportDates:
  start: 10/12/2016
  end: 10/12/2021
  extendedEnd: 01/12/2027
releases:
- version: Original Release
  startDate: 10/12/2016
  endDate: 01/12/2027
content: "\n## <a name=\"links\"></a>Hivatkozások \n* [Karbantartási és támogatási információk](/sccm/core/understand/learn-more-editions)"
