### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
  description: A Microsoft Application Virtualization Hosting 4.6 Windows Asztali számítógépekre a Rögzített Életciklus Szabályzatot követi.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
summary: |+
  A Microsoft Application Virtualization Hosting 4.6 Windows Asztali számítógépekre a [Rögzített](/lifecycle/policies/fixed) Életciklus Szabályzatot követi.

  Ez a következő kiadásokra vonatkozik: Windows asztali gépekre

products:
  - windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
  - version: Service Pack 3
    startDate: 12/02/2013
    endDate: 07/14/2020
  - version: Service Pack 2
    startDate: 10/01/2012
    endDate: 01/13/2015
  - version: Service Pack 1
    startDate: 01/26/2011
    endDate: 10/08/2013
  - version: Original Release
    startDate: 05/27/2010
    endDate: 04/10/2012
content: |

  ## <a name="links"></a>Hivatkozások 
  * [Termék- és áttelepítési információk](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Szervizcsomag-szabályzat](/lifecycle/policies/fixed#service-packs)

  > [!NOTE]
  > Mivel az App-V 4.6 ügyfél az App-V 4.5 Servert használja, az App-V 4.5 Server továbbra is támogatott lesz az App-V 4.6 életciklus dátumainak megfelelően, ha azt a támogatott App-V 4.6 ügyféllel használja.

  ## <a name="editions"></a>Kiadások 
  * Windows asztali számítógépek esetén