### YamlMime:Lifecycle
metadata:
  title: Microsoft alkalmazás virtualizáció5.0
  description: A Microsoft Application Virtualization 5.0 a Rögzített életciklus-szabályzatot követi.
  ms.date: 07/28/2020
  ms.openlocfilehash: 537410789f17e2ca2d9308c1814f22f823288b32
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "855864"
name: Microsoft alkalmazás virtualizáció5.0
summary: >+
  A Microsoft Application Virtualization 5.0 a [Rögzített](/lifecycle/policies/fixed) életciklus-szabályzatot követi.


  Ez a következő kiadásokra vonatkozik: Távoli asztali szolgáltatások, terminálszolgáltatások, Windows asztali számítógépek esetén

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 01/10/2023
releases:
- version: Service Pack 3
  startDate: 12/08/2014
  endDate: 01/10/2023
- version: Service Pack 2
  startDate: 12/02/2013
  endDate: 01/12/2016
- version: Service Pack 1
  startDate: 04/10/2013
  endDate: 01/13/2015
- version: Original Release
  startDate: 11/01/2012
  endDate: 07/08/2014
content: "\n## <a name=\"links\"></a>Linkek \n* [Termékinformációk](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n* [Szervizcsomag házirendje](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Kiadások \n* távoli asztali szolgáltatásokhoz\n* terminálszolgáltatásokhoz\n* Windows asztali számítógépekhez"
