### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 R2 Konfigurációkezelő
  description: A Microsoft System Center 2012 R2 Konfigurációkezelő a Rögzített Életciklus Szabályzatot követi.
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: b9a1c0fa5804c5929f39f72816e86e49c739d281
  ms.sourcegitcommit: 8465b0fa45ee2c451d1f1eaf7be9a1544cdad17f
  ms.translationtype: HT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 03/12/2021
  ms.locfileid: "1462909"
name: Microsoft System Center 2012 R2 Konfigurációkezelő
summary: >+
  A Microsoft System Center 2012 R2 Konfigurációkezelő a [Rögzített](/lifecycle/policies/fixed) Életciklus Szabályzatot követi.


products:
- msc
policyType: fixed
supportDates:
  start: 01/16/2014
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 1
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Original Release
  startDate: 01/16/2014
  endDate: 07/12/2016
content: "\n## <a name=\"links\"></a>Hivatkozások \n* [Szervizcsomag-szabályzat](/lifecycle/policies/fixed#service-packs)\n* [A Konfigurációkezelő dokumentációja](/mem/configmgr/core/misc/online-documentation)\n* [Áttelepítési útmutató](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
