### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: A Microsoft System Center Configuration Manager 2007 R3 a Rögzített Életciklus Szabályzatot követi.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  A Microsoft System Center Configuration Manager 2007 R3 a [Rögzített](/lifecycle/policies/fixed) Életciklus Szabályzatot követi.


  > [!IMPORTANT]
  > A termék támogatása lejárt. Lásd lejjebb az áttelepítési útmutatót.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Hivatkozások 
  * [Áttelepítési útmutató](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [További áttelepítési útmutató](/mem/configmgr/core/migration/planning-for-migration)