### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 Windows asztali gépekre
  description: A Microsoft Application Virtualization Hosting 5.1 for Windows Desktops a Rögzített Életciklus Szabályzatot követi.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: HT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "856044"
name: Microsoft Application Virtualization Hosting 5.1 Windows asztali gépekre
summary: >+
  A Microsoft Application Virtualization Hosting 5.1 for Windows Desktops a [Rögzített](/lifecycle/policies/fixed) Életciklus Szabályzatot követi.


  Ez a következő kiadásokra vonatkozik: Windows asztali gépekre

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Hivatkozások \n* [Termékinformációk](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Kiadások \n* Windows asztali számítógépek esetén"
