### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: A Microsoft Application Virtualization 5.1 a Rögzített Életciklus Szabályzatot követi.
  ms.date: 09/10/2020
  keywords: 'for Remote Desktop Services,for Windows Desktops'
name: Microsoft Application Virtualization 5.1
summary: |+
  A Microsoft Application Virtualization 5.1 a [Rögzített](/lifecycle/policies/fixed) Életciklus Szabályzatot követi.

  Ez a következő kiadásokra vonatkozik: Távoli asztali szolgáltatásokhoz, Windows asztali számítógépekhez

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Hivatkozások 
  * [Termékinformációk](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)


  ## <a name="editions"></a>Kiadások 
  * távoli asztali szolgáltatásokhoz
  * Windows asztali számítógépek esetén