### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 Konfigurációkezelő
  description: A Microsoft System Center 2012 Configuration Manager a rögzített életciklus-szabályzatot követi.
  ms.date: 07/28/2020
  ms.openlocfilehash: dce8796f280b29e070bbf1d5bab55452f6e706e7
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "855931"
name: Microsoft System Center 2012 Konfigurációkezelő
summary: >+
  A Microsoft System Center 2012 Configuration Manager a [rögzített](/lifecycle/policies/fixed) életciklus-szabályzatot követi.


products:
- msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 2
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Service Pack 1
  startDate: 12/15/2012
  endDate: 07/12/2016
- version: Original Release
  startDate: 05/30/2012
  endDate: 01/14/2014
content: "\n## <a name=\"links\"></a>Linkek \n* [Szervizcsomag házirendje](/lifecycle/policies/fixed#service-packs)\n* [System Center dokumentáció](/system-center/#pivot=components&panel=components-all)\n* [Rendszerközpont-erőforrások](https://www.microsoft.com/system-center/resources)"
