### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: A Microsoft System Center Configuration Manager 2007 R3 a rögzített életciklusra vonatkozó szabályzatot követi.
  ms.date: 07/28/2020
  ms.openlocfilehash: cffcc1c2bb51fc5023fe6ad29d62132141ffedb2
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "856145"
name: Microsoft System Center Configuration Manager 2007 R3
summary: >
  A Microsoft System Center Configuration Manager 2007 R3 a rögzített életciklusra [vonatkozó](/lifecycle/policies/fixed) szabályzatot követi.



  > [!IMPORTANT]

  > A termék támogatása véget ért. Lásd az áttelepítési útmutatót alább.
products:
- msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 12/19/2010
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Linkek \n* [Migrációs útmutató](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [További áttelepítési útmutató](/mem/configmgr/core/migration/planning-for-migration)"
