### YamlMime:Lifecycle
metadata:
  title: Microsoft alkalmazás virtualizáció5.1
  description: A Microsoft Application Virtualization 5.1 a Rögzített életciklus-szabályzatot követi.
  ms.date: 07/28/2020
  ms.openlocfilehash: 3f0cac2ee013dd73e44fe41d9ba1d07cfcfce2f1
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "855862"
name: Microsoft alkalmazás virtualizáció5.1
summary: >+
  A Microsoft Application Virtualization 5.1 a [Rögzített](/lifecycle/policies/fixed) életciklus-szabályzatot követi.


  Ez a következő kiadásokra vonatkozik: Távoli asztali szolgáltatások esetén, Windows asztali számítógépek esetén

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Linkek \n* [Termékinformációk](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Kiadások \n* távoli asztali szolgáltatásokhoz\n* Windows asztali számítógépekhez"
