### YamlMime:Lifecycle
metadata:
  title: SoftGrid alkalmazás virtualizálása
  description: SoftGrid alkalmazás virtualizálás követi a rögzített életciklus-szabályzat.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "821650"
name: SoftGrid alkalmazás virtualizálása
summary: >
  SoftGrid alkalmazás virtualizálás követi a [rögzített](/lifecycle/policies/fixed) életciklus-szabályzat.


  Ez a következő kiadásokra vonatkozik: 4.1 asztali számítógépekhez, 4.2 asztali számítógépekhez, Terminálszolgáltatások 4.1 esetén


  > [!IMPORTANT]

  > A támogatás véget ért. Lásd az áttelepítési útmutatót alább.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Linkek \n* [Migrációs útmutató](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Kiadások \n* 4.1 asztali számítógépekhez\n* 4.2 asztali számítógépekhez\n* terminálszolgáltatások esetén 4.1"
